apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoservice
  template:
    metadata:
      labels:
        app: autoservice
    spec:
      containers:
        - name: autoservice
          image: autoservice-app
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
