apiVersion: v1
kind: Service
metadata:
  name: autoservice-service
spec:
  type: NodePort
  selector:
    app: autoservice
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30001
